//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhantasmaMail.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhantasmaMail.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Key.
        /// </summary>
        public static string Button_EncryptedKey {
            get {
                return ResourceManager.GetString("Button_EncryptedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIF.
        /// </summary>
        public static string Button_WIF {
            get {
                return ResourceManager.GetString("Button_WIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Key.
        /// </summary>
        public static string Entry_EncryptedKey_Text {
            get {
                return ResourceManager.GetString("Entry_EncryptedKey_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Entry_Password_Text {
            get {
                return ResourceManager.GetString("Entry_Password_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIF.
        /// </summary>
        public static string Entry_WIF_Text {
            get {
                return ResourceManager.GetString("Entry_WIF_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose.
        /// </summary>
        public static string MenuItem_Compose {
            get {
                return ResourceManager.GetString("MenuItem_Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string MenuItem_Important {
            get {
                return ResourceManager.GetString("MenuItem_Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string MenuItem_Inbox {
            get {
                return ResourceManager.GetString("MenuItem_Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MenuItem_Logout {
            get {
                return ResourceManager.GetString("MenuItem_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string MenuItem_Sent {
            get {
                return ResourceManager.GetString("MenuItem_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuItem_Settings {
            get {
                return ResourceManager.GetString("MenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string MenuItem_Trash {
            get {
                return ResourceManager.GetString("MenuItem_Trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string MenuItem_Wallet {
            get {
                return ResourceManager.GetString("MenuItem_Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGE.
        /// </summary>
        public static string PageTitle_Compose {
            get {
                return ResourceManager.GetString("PageTitle_Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INBOX.
        /// </summary>
        public static string PageTitle_Inbox {
            get {
                return ResourceManager.GetString("PageTitle_Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENT.
        /// </summary>
        public static string PageTitle_Sent {
            get {
                return ResourceManager.GetString("PageTitle_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WALLET.
        /// </summary>
        public static string PageTitle_Wallet {
            get {
                return ResourceManager.GetString("PageTitle_Wallet", resourceCulture);
            }
        }
    }
}
